### ISSUE TITLE
dataset

### ISSUE THREAD

**Issue by zahrabsh74** [matciotola/Lambda-PNN#1]
Hello @matciotola 
Thank you for your great work!
I get interested in your code and I wanted to run it but I have a question about the dataset that you used for training. Is it free and accessible data for the public? if yes, how can I achieve this dataset? if not, do you have any suggestions on what other free datasets are available and similar to the one you have used?

**Comment by matciotola** [comment]
Dear @zahrabsh74 ,
Unfortunately, the dataset is not available. I provided the pre-trained weights for reproducibility. 
However, some test datasets are accessible ([PairMax](https://resources.maxar.com/product-samples/pansharpening-benchmark-dataset)). 
To the best of my knowledge, just a free and accessible dataset is available:

X. Meng et al., “A Large-Scale Benchmark Data Set for Evaluating Pansharpening Performance: Overview and Implementation,” IEEE Geosci. Remote Sens. Mag., vol. 9, no. 1, pp. 18–52, Mar. 2021, doi: [10.1109/MGRS.2020.2976696](https://doi.org/10.1109/MGRS.2020.2976696).

[NBU Dataset](https://pan.baidu.com/s/1Utja1PHUqgoXaksWjC2CPw).

I do not know the content, but you could try it. 
Otherwise, as a last option, you could collect some sample images from the Maxar website (many of the images used in my dataset are sample images, like WorldView-3 Adelaide).

Let me know,
Matteo

**Comment by zahrabsh74** [comment]
Dear @matciotola. thank you so much for your answer. I tried to use your pre-trained weights on Pairmax dataset which you recommended. Meanwhile, I tried to train your model on my dataset which is satellite images from worldview3. But your checkpoint's result has better performance than my own trained/finetuned model. I want to ask if should I make any changes in spectral_tools.py and make any changes in its parameters? As I didn't completely understand "nyquist_gain" in spectral_tools.py I asked you this question.

**Comment by matciotola** [comment]
Dear @zahrabsh74 
It could depend on several factors.
First of all, how do you evaluate your results?
How many images do you use for training, and with which size? Did you correctly save them in mat format, respecting the dictionary nomenclature?
If I understood well, you have re-trained the algorithm on your dataset and tested it on the PairMax dataset, didn't you?
Did you run the train.py (python train.py -s WV3 -i path/to/your/dataset --from_scratch), and the test.py applying correctly the target adapting phase (python test.py -i path/to/pairmax.mat -s WV3), modifying the weight paths in the file?

The problem is surely not the spectral_tool.py file, being the nyquist_gains specific of the satellites. These gains are responsible for the generation of the Gaussian which simulates the Modulation Transfer Function for any band. You can find more details about it in the literature. This filter is used by most algorithms for pansharpening and it should not differ from one algorithm to another.

Please, if you encounter other problems send me an e-mail to matteo.ciotola[at]unina.it
